### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Flippi1990** [UsainSrht/AutoTool#2]
hey, nice plugin.

its possible to use it with a permission? that player can buy this feature. nad maybe a command

**Comment by UsainSrht** [comment]
Sounds like a good idea. I will implement it 👍

**Comment by Flippi1990** [comment]
nice thx

**Comment by Flippi1990** [comment]
you know when the update is coming?

**Comment by UsainSrht** [comment]
Temporarly added in 25e1cd4
[AutoTool-1.1.zip](https://github.com/UsainSrht/AutoTool/files/14130243/AutoTool-1.1.zip)

This will be officially support with the upcoming 1.2 update which will also add invidual toggling for autotool as well as configurable permission.
